# Generated by Django 3.0.3 on 2020-06-28 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kaufdatum', models.DateField(default=datetime.date.today)),
                ('menge', models.IntegerField()),
                ('lagerort', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kaufdatum', models.DateField(default=datetime.date.today)),
                ('menge', models.IntegerField()),
                ('lagerort', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Saeuren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kaufdatum', models.DateField(default=datetime.date.today)),
                ('menge', models.IntegerField()),
                ('lagerort', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
