# Generated by Django 3.0.3 on 2020-06-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basen',
            name='status',
            field=models.CharField(choices=[('VORHANDEN', 'Dieser Stoff befindet sich in der Sammlung'), ('LEER', 'Dieser Stoff befindet sich nicht mehr in der Sammlung'), ('BESTELLT', 'Diser Stoff wurde bestellt und befindet sich in der Lieferung')], default='LEER', max_length=10),
        ),
        migrations.AddField(
            model_name='metalle',
            name='status',
            field=models.CharField(choices=[('VORHANDEN', 'Dieser Stoff befindet sich in der Sammlung'), ('LEER', 'Dieser Stoff befindet sich nicht mehr in der Sammlung'), ('BESTELLT', 'Diser Stoff wurde bestellt und befindet sich in der Lieferung')], default='LEER', max_length=10),
        ),
        migrations.AddField(
            model_name='saeuren',
            name='status',
            field=models.CharField(choices=[('VORHANDEN', 'Dieser Stoff befindet sich in der Sammlung'), ('LEER', 'Dieser Stoff befindet sich nicht mehr in der Sammlung'), ('BESTELLT', 'Diser Stoff wurde bestellt und befindet sich in der Lieferung')], default='LEER', max_length=10),
        ),
    ]
