# Generated by Django 3.0.3 on 2020-06-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200628_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='basen',
            name='art',
            field=models.CharField(choices=[('ml', 'milliliter'), ('l', 'liter'), ('g', 'gramm'), ('kg', 'kilogramm')], default='ml', max_length=10),
        ),
        migrations.AddField(
            model_name='metalle',
            name='art',
            field=models.CharField(choices=[('ml', 'milliliter'), ('l', 'liter'), ('g', 'gramm'), ('kg', 'kilogramm')], default='ml', max_length=10),
        ),
        migrations.AddField(
            model_name='saeuren',
            name='art',
            field=models.CharField(choices=[('ml', 'milliliter'), ('l', 'liter'), ('g', 'gramm'), ('kg', 'kilogramm')], default='ml', max_length=10),
        ),
    ]
